#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
import argparse
import sys


def main(argv):
    parser = argparse.ArgumentParser(description="FolderME music player")
    parser.add_argument(
        "--remote", metavar="CMD", help="send CMD to FolderME dbus service"
    )
    parser.add_argument(
        "--show", action="store_true", default=False, help="show UI on startup"
    )
    parser.add_argument(
        "--no-dbus",
        action="store_true",
        default=False,
        help="do not start dbus service",
    )
    parser.add_argument(
        "--no-lastfm",
        action="store_true",
        default=False,
        help="do not scrobble to last.fm",
    )
    parser.add_argument(
        "--no-save",
        action="store_true",
        default=False,
        help="do not save application state",
    )
    args = parser.parse_args(argv[1:])

    if args.remote:
        import remote

        remote.send(args.remote)
        sys.exit(0)
    else:
        import app

        app.start(args)


if __name__ == "__main__":
    main(sys.argv)
